/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jmultigwas;

import java.awt.Component;
import javax.swing.JOptionPane;

/**
 *
 * @author lg
 */
public class ViewToolBar extends javax.swing.JPanel {
    Controller controller;

    public ViewToolBar(Controller controller) {
        this.controller = controller;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator7 = new javax.swing.JSeparator();
        jToolBar1 = new javax.swing.JToolBar();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        jSeparator2 = new javax.swing.JToolBar.Separator();
        jSeparator3 = new javax.swing.JToolBar.Separator();
        jSeparator4 = new javax.swing.JToolBar.Separator();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator6 = new javax.swing.JSeparator();
        buttonNew = new javax.swing.JButton();
        jSeparator8 = new javax.swing.JSeparator();
        buttonDefaults = new javax.swing.JButton();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator9 = new javax.swing.JSeparator();
        buttonQuit = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        jToolBar1.setBackground(new java.awt.Color(153, 255, 153));
        jToolBar1.setFloatable(false);
        jToolBar1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jToolBar1.setPreferredSize(new java.awt.Dimension(155, 50));
        jToolBar1.add(jSeparator1);
        jToolBar1.add(jSeparator2);
        jToolBar1.add(jSeparator3);
        jToolBar1.add(jSeparator4);

        jPanel1.setBackground(new java.awt.Color(153, 255, 153));

        jLabel1.setBackground(new java.awt.Color(153, 255, 153));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("MultiGWAS");
        jLabel1.setMaximumSize(new java.awt.Dimension(120, 100));
        jLabel1.setOpaque(true);
        jLabel1.setPreferredSize(new java.awt.Dimension(80, 100));
        jPanel1.add(jLabel1);
        jPanel1.add(jSeparator6);

        buttonNew.setText("<html>New MultiGWAS analysis</html>");
        buttonNew.setPreferredSize(new java.awt.Dimension(150, 50));
        buttonNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonNewActionPerformed(evt);
            }
        });
        jPanel1.add(buttonNew);

        jSeparator8.setPreferredSize(new java.awt.Dimension(50, 5));
        jPanel1.add(jSeparator8);

        buttonDefaults.setText("<html>Set default values</html>");
        buttonDefaults.setPreferredSize(new java.awt.Dimension(145, 50));
        buttonDefaults.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonDefaultsActionPerformed(evt);
            }
        });
        jPanel1.add(buttonDefaults);
        jPanel1.add(jSeparator5);

        jSeparator9.setPreferredSize(new java.awt.Dimension(50, 5));
        jPanel1.add(jSeparator9);

        buttonQuit.setText("<html>Quit</html>");
        buttonQuit.setPreferredSize(new java.awt.Dimension(145, 50));
        buttonQuit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonQuitActionPerformed(evt);
            }
        });
        jPanel1.add(buttonQuit);

        jToolBar1.add(jPanel1);

        add(jToolBar1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void buttonDefaultsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonDefaultsActionPerformed
        controller.onDefaultButton ();        // TODO add your handling code here:
    }//GEN-LAST:event_buttonDefaultsActionPerformed

    private void buttonQuitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonQuitActionPerformed
        int result = JOptionPane.showConfirmDialog((Component) null, 
                "Do you really want to exit from MultiGWAS?",
                "Exit MultiGWAS", JOptionPane.OK_CANCEL_OPTION);   
        if (result==JOptionPane.OK_OPTION) {
            System.exit (0);
        }
    }//GEN-LAST:event_buttonQuitActionPerformed

    private void buttonNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonNewActionPerformed
        int result = JOptionPane.showConfirmDialog((Component) null, 
                "Do you really want to start a new MultiGWAS?",
                "Exit MultiGWAS", JOptionPane.OK_CANCEL_OPTION);   
        if (result==JOptionPane.OK_OPTION) {
            controller.onNewButton ();
        }
    }//GEN-LAST:event_buttonNewActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonDefaults;
    private javax.swing.JButton buttonNew;
    private javax.swing.JButton buttonQuit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JToolBar.Separator jSeparator2;
    private javax.swing.JToolBar.Separator jSeparator3;
    private javax.swing.JToolBar.Separator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JToolBar jToolBar1;
    // End of variables declaration//GEN-END:variables
}
